source "proxmox-iso" "autogenerated_1" {
  vm_id        = var.vm_id
  # boot_command = ["<up><tab> text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter>"]
  boot_command = ["<tab> text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"]
  boot_wait    = var.vm_boot_wait
  cores        = var.vm_vcpus
  cpu_type     = "Nehalem"
  disks {
    disk_size    = var.vm_disk_size
    storage_pool = var.proxmox_storage_pool
    type         = var.vm_disk_type
    format       = var.disk_format
  }
  cloud_init               = var.cloud_init
  cloud_init_storage_pool  = var.proxmox_storage_pool
#   http_directory           = var.http_directory
  http_content = {
    "/ks.cfg" = templatefile("http/ks.cfg.pkrtpl", var)
  }

  insecure_skip_tls_verify = var.proxmox_insecure_skip_tls_verify
  iso_file                 = "${var.proxmox_iso_pool}/${var.rocky9_image}"
  memory                   = var.vm_memory
  network_adapters {
    bridge = var.vm_network_adapters_bridge
    model  = var.vm_network_adapters_model
  }
  efi_config {
    efi_storage_pool  = var.proxmox_storage_pool
    efi_type          = var.efi_config_type
    pre_enrolled_keys = var.efi_config_pre_enrolled_keys
  }
  node = var.proxmox_node
  os   = var.vm_os
  # password             = "${var.proxmox_password}"
  token                = var.proxmox_token
  proxmox_url          = var.proxmox_url
  scsi_controller      = var.vm_scsi_controller
  ssh_password         = var.ssh_password
  ssh_port             = var.ssh_port
  ssh_timeout          = var.ssh_timeout
  ssh_username         = var.ssh_username
  template_description = var.template_description
  template_name        = var.template_name
  unmount_iso          = var.unmount_iso
  username             = var.proxmox_username
}

build {
  sources = ["source.proxmox-iso.autogenerated_1"]

  provisioner "shell" {
    inline = [
        "sudo yum install -y cloud-init qemu-guest-agent cloud-utils-growpart gdisk", 
        "sudo shred -u /etc/ssh/*_key /etc/ssh/*_key.pub", 
        "sudo rm -f /var/run/utmp",
        "sudo rm -rf /tmp/* /var/tmp/*", 
        "sudo rm -rf /home/*/.*history",
        "sudo rm -rf /root/.*history", 
        "sudo rm -f /root/*ks", 
        "sudo passwd -d root", 
        "sudo passwd -l root",
        "sudo sed -i 's/#PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config",
        "sudo systemctl restart sshd",
        "sudo yum update -y"
        ]
  }
  provisioner "shell" "adjusting_ssh_key" {
    inline = [
      "sudo mkdir -p /infra/.ssh",
      "sudo chmod 700 /infra/.ssh",
      "sudo echo $SSH_PUBLIC_KEY > /infra/.ssh/authorized_keys",
      "sudo chmod 600 /infra/.ssh/authorized_keys",
      "sudo chown -R infra:infra /infra/.ssh"
    ]
  }

  provisioner "ansible" {
    groups        = ["linux"]
    playbook_file = "./rocky_linux_9/ansible/main.yml"
    extra_arguments = [
      "-vvv",
      "-e vra=false",
      "-e ansible_port=22",
      "-e ansible_host=${build.Host}",
      "-e ansible_user=${build.User}",
      "-e ansible_password=${build.Password}"
    ]
  }
}
