name: Build Template Oracle Linux 8

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  run_scripts:
    runs-on:
    - self-hosted
    - packer

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Remove Template
      run: |
        ansible-playbook ./oracle_linux_8/ansible/remove_template.yml \
          -e "api_user=${{ vars.PROXMOX_API_USER }}" \
          -e "api_token_id=${{ vars.PROXMOX_TOKEN_ID }}" \
          -e "api_token_secret=${{ secrets.PROXMOX_TOKEN }}" \
          -e "api_host=${{ secrets.PROXMOX_API_HOST }}" \
          -e "vmid=${{ vars.PROXMOX_VM_ID }}" \
          -e "node=${{ vars.PROXMOX_NODE }}"           

    - name: Init Template
      run:
        packer init -upgrade oracle_linux_8/
      env:
        PKR_VAR_proxmox_url: ${{ secrets.PROXMOX_URL }}
        PKR_VAR_proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
        PKR_VAR_proxmox_token: ${{ secrets.PROXMOX_TOKEN }}
        PKR_VAR_proxmox_node: ${{ vars.PROXMOX_NODE }}
        PKR_VAR_proxmox_storage_pool: ${{ vars.PROXMOX_STORAGE_POOL }}
        PKR_VAR_ssh_username: ${{ vars.SSH_USERNAME }}
        PKR_VAR_ssh_password: ${{ secrets.SSH_PASSWORD }}
    
    - name: Build Template
      run:
         packer build oracle_linux_8/
      env:
        PKR_VAR_proxmox_url: ${{ secrets.PROXMOX_URL }}
        PKR_VAR_proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
        PKR_VAR_proxmox_token: ${{ secrets.PROXMOX_TOKEN }}
        PKR_VAR_proxmox_node: ${{ vars.PROXMOX_NODE }}
        PKR_VAR_proxmox_storage_pool: ${{ vars.PROXMOX_STORAGE_POOL }}
        PKR_VAR_ssh_username: ${{ vars.SSH_USERNAME }}
        PKR_VAR_ssh_password: ${{ secrets.SSH_PASSWORD }}
